version: 1.0.{build}
configuration: Debug
platform: Any CPU
before_build:
- cmd: nuget restore ./Challenge.sln
build:
  project: Source/Source.csproj
  verbosity: normal
before_test:
- cmd: dir
test:
  assemblies:
    only:
    - '**\*.Source.Test.dll'
