version: 1.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
before_test:
- cmd: >-
    dir

    cd Source.Test

    dir
